# Generated by Django 2.2.16 on 2022-05-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20220511_0147'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique follow'),
        ),
    ]
