# Generated by Django 2.2.16 on 2022-09-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20220511_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('Ip', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
